"""Adiciona nova tabela ao banco de dados

Revision ID: e4a545c68f0a
Revises: f4447673777d
Create Date: 2026-09-12 16:02:54.706302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a545c68f0a'
down_revision = 'f4447673777d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fila_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinatario', sa.String(length=120), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('reply_to', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.alter_column('preco_unitario',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.alter_column('preco_unitario',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    op.drop_table('fila_emails')
    # ### end Alembic commands ###
